---
title: "TestImputeTS"
author: "Sophia Ding"
date: "7/8/2019"
output: html_document
---
```{r,message=FALSE}
dataset <- read.delim("~/Desktop/dataset.s010")
library("imputeTS")
library("MyPackage")
library("zoo")
library("varhandle")
```

```{r}
cleandata = clean(dataset)
data = aList(cleandata)
#imputation by imputeTS package
impu <- naInsert(data[[1]])
t <- impu[,1]
x0 <- x <- zoo(unfactor(impu[,3]), t)
# set 10 missing values
x[c(61:70)] <- NA
# fit model
#Use na_interpolation

#Imputation by: "linear" - for linear interpolation using approx
fit <- na_interpolation(x, option = "linear", maxgap = Inf)
id.na <- which(is.na(x))

#plot
par(mfrow = c(2, 1), mar = c(2.7,2.7,2,2))
plot(x0, col = "grey", xlab = "DisplayTime", ylab = "GlucoseValue")
lines(x)
points(t[id.na], x0[id.na], col = "blue", pch = 19)
points(t[id.na], fit[id.na], col = "red", pch = 17)
legend("topright", legend = c("true values", "imputed values"), col = c("blue", "red"), pch = c(19, 17))

plot(t[61:70], x0[61:70], type = "b", col = "blue", pch = 19, ylim = range(fit[61:70]), xlab = "DisplayTime", ylab = "GlucoseValue")
points(t[61:70], fit[61:70], col = "red", pch = 17)
lines(t[61:70], fit[61:70], col = "red")
legend("topright", legend = c("true values", "imputed values"), col = c("blue", "red"), pch = c(19, 17), lty = c(1, 1))
```
```{r}
cleandata = clean(dataset)
data = aList(cleandata)
#imputation by imputeTS package
#linear (approx)
impu <- naInsert(data[[1]])
t <- impu[,1]
x0 <- x <- zoo(unfactor(impu[,3]), t)
# set 10 missing values
x[c(61:70)] <- NA
# fit model
#Use na_interpolation

#Imputation by: "linear" - for linear interpolation using approx
fit <- na_interpolation(x, option = "linear", maxgap = Inf)
id.na <- which(is.na(x))

#plot
par(mfrow = c(2, 1), mar = c(2.7,2.7,2,2))
plot(x0, col = "grey", xlab = "DisplayTime", ylab = "GlucoseValue")
lines(x)
points(t[id.na], x0[id.na], col = "blue", pch = 19)
points(t[id.na], fit[id.na], col = "red", pch = 17)
legend("topright", legend = c("true values", "imputed values"), col = c("blue", "red"), pch = c(19, 17))

plot(t[61:70], x0[61:70], type = "b", col = "blue", pch = 19, ylim = range(fit[61:70]), xlab = "DisplayTime", ylab = "GlucoseValue")
points(t[61:70], fit[61:70], col = "red", pch = 17)
lines(t[61:70], fit[61:70], col = "red")
legend("topright", legend = c("true values", "imputed values"), col = c("blue", "red"), pch = c(19, 17), lty = c(1, 1))
```

```{r}
#imputation by imputeTS package
#spline
impu <- naInsert(data[[1]])
t <- impu[,1]
x0 <- x <- zoo(unfactor(impu[,3]), t)
# set 10 missing values
x[c(61:70)] <- NA
# fit model
#Use na_interpolation

#Imputation by: "linear" - for linear interpolation using approx
fit <- na_interpolation(x, option = "linear", maxgap = Inf)
id.na <- which(is.na(x))

#plot
par(mfrow = c(2, 1), mar = c(2.7,2.7,2,2))
plot(x0, col = "grey", xlab = "DisplayTime", ylab = "GlucoseValue")
lines(x)
points(t[id.na], x0[id.na], col = "blue", pch = 19)
points(t[id.na], fit[id.na], col = "red", pch = 17)
legend("topright", legend = c("true values", "imputed values"), col = c("blue", "red"), pch = c(19, 17))

plot(t[61:70], x0[61:70], type = "b", col = "blue", pch = 19, ylim = range(fit[61:70]), xlab = "DisplayTime", ylab = "GlucoseValue")
points(t[61:70], fit[61:70], col = "red", pch = 17)
lines(t[61:70], fit[61:70], col = "red")
legend("topright", legend = c("true values", "imputed values"), col = c("blue", "red"), pch = c(19, 17), lty = c(1, 1))
```
```{r}
#imputation by imputeTS package
impu <- naInsert(data[[1]])
t <- impu[,1]
x0 <- x <- zoo(unfactor(impu[,3]), t)
# set 10 missing values
x[c(61:70)] <- NA
# fit model
#Use na_interpolation

#Imputation by: "linear" - for linear interpolation using approx
fit <- na_interpolation(x, option = "spline", maxgap = Inf)
id.na <- which(is.na(x))

#plot
par(mfrow = c(2, 1), mar = c(2.7,2.7,2,2))
plot(x0, col = "grey", xlab = "DisplayTime", ylab = "GlucoseValue")
lines(x)
points(t[id.na], x0[id.na], col = "blue", pch = 19)
points(t[id.na], fit[id.na], col = "red", pch = 17)
legend("topright", legend = c("true values", "imputed values"), col = c("blue", "red"), pch = c(19, 17))

plot(t[61:70], x0[61:70], type = "b", col = "blue", pch = 19, ylim = range(fit[61:70]), xlab = "DisplayTime", ylab = "GlucoseValue")
points(t[61:70], fit[61:70], col = "red", pch = 17)
lines(t[61:70], fit[61:70], col = "red")
legend("topright", legend = c("true values", "imputed values"), col = c("blue", "red"), pch = c(19, 17), lty = c(1, 1))
```
```{r}
cleandata = clean(dataset)
data = aList(cleandata)
#imputation by imputeTS package
impu <- naInsert(data[[1]])
t <- impu[,1]
x0 <- x <- zoo(unfactor(impu[,3]), t)
# set 10 missing values
x[c(61:70)] <- NA
# fit model
#Use na_interpolation

#Imputation by: "linear" - for linear interpolation using approx
fit <- na_interpolation(x, option = "linear", maxgap = Inf)
id.na <- which(is.na(x))

#plot
par(mfrow = c(2, 1), mar = c(2.7,2.7,2,2))
plot(x0, col = "grey", xlab = "DisplayTime", ylab = "GlucoseValue")
lines(x)
points(t[id.na], x0[id.na], col = "blue", pch = 19)
points(t[id.na], fit[id.na], col = "red", pch = 17)
legend("topright", legend = c("true values", "imputed values"), col = c("blue", "red"), pch = c(19, 17))

plot(t[61:70], x0[61:70], type = "b", col = "blue", pch = 19, ylim = range(fit[61:70]), xlab = "DisplayTime", ylab = "GlucoseValue")
points(t[61:70], fit[61:70], col = "red", pch = 17)
lines(t[61:70], fit[61:70], col = "red")
legend("topright", legend = c("true values", "imputed values"), col = c("blue", "red"), pch = c(19, 17), lty = c(1, 1))
```
```{r}
#imputation by imputeTS package
#stine (stinterp)
impu <- naInsert(data[[1]])
t <- impu[,1]
x0 <- x <- zoo(unfactor(impu[,3]), t)
# set 10 missing values
x[c(61:70)] <- NA
# fit model
#Use na_interpolation

#Imputation by: "linear" - for linear interpolation using approx
fit <- na_interpolation(x, option = "stine", maxgap = Inf)
id.na <- which(is.na(x))

#plot
par(mfrow = c(2, 1), mar = c(2.7,2.7,2,2))
plot(x0, col = "grey", xlab = "DisplayTime", ylab = "GlucoseValue")
lines(x)
points(t[id.na], x0[id.na], col = "blue", pch = 19)
points(t[id.na], fit[id.na], col = "red", pch = 17)
legend("topright", legend = c("true values", "imputed values"), col = c("blue", "red"), pch = c(19, 17))

plot(t[61:70], x0[61:70], type = "b", col = "blue", pch = 19, ylim = range(fit[61:70]), xlab = "DisplayTime", ylab = "GlucoseValue")
points(t[61:70], fit[61:70], col = "red", pch = 17)
lines(t[61:70], fit[61:70], col = "red")
legend("topright", legend = c("true values", "imputed values"), col = c("blue", "red"), pch = c(19, 17), lty = c(1, 1))
```

