---
title: "zoo_spline_pre_dia"
output: html_document
---
```{r}
series <- read.delim("~/Desktop/dataset.s010")
series = na.omit(series)
library(varhandle)
library(zoo)
library(zoo)
library(DTWBI)
library(openair)
```

Pre-dia 
na.spline error lists for plotting
```{r}
mad_spline_zoo = c()
frac_bias_spline_zoo = c()
rmse_spline_zoo = c()
ioa_spline_zoo = c()
```

Pre-dia "2133-017"
Method = {zoo}na.spline
```{r}
pre_dia = subset(series, series[,3] == "2133-017")
```

Gap = 5
```{r}
mad_spline_5_zoo = c()
fractional_bias_spline_5_zoo = c()
rmse_spline_5_zoo = c()
ioa_spline_5_zoo = c()
```

```{r}
seed_points <- sample(1:1500, 100, replace = FALSE)
```

```{r}
for (i in seed_points) { 
  series_new = pre_dia
  for (j in 0:4) { 
    series_new$GlucoseValue[i+j] = NA
  }
  series_new$GlucoseValue = na.spline(unfactor(series_new$GlucoseValue))
    
  #calculating mean absolute difference
  temp1 = mad(series_new$GlucoseValue)
  mad_spline_5_zoo = c(mad_spline_5_zoo,temp1)
    
  #calculating fractional bias
  temp2 = compute.fb(series_new$GlucoseValue, unfactor(pre_dia$GlucoseValue))
  fractional_bias_spline_5_zoo = c(fractional_bias_spline_5_zoo, temp2)
    
  #calculating RMSE
  temp3 = compute.rmse(series_new$GlucoseValue, unfactor(pre_dia$GlucoseValue))
  rmse_spline_5_zoo = c(rmse_spline_5_zoo,temp3)
  
  #calculatind IOA
  x = data.frame("real" = unfactor(pre_dia$GlucoseValue), 'imputed' = series_new$GlucoseValue)
  temp4 = modStats(x,mod = "imputed",obs = "real", statistic = c("IOA"))
  ioa_spline_5_zoo = c(ioa_spline_5_zoo, temp4$IOA)
}
```
 
```{r}
mean_fractional_bias_spline_5 = mean(fractional_bias_spline_5_zoo)
cat("Mean Fractional Bias for na.spline method with Gap Value of 5 is ",mean_fractional_bias_spline_5, "thats is, ",mean_fractional_bias_spline_5*100,"%\n\n")
mean_rmse_spline_5 = mean(rmse_spline_5_zoo)
cat("Mean RMSE for na.spline method with Gap Value of 5 is ",mean_rmse_spline_5, "thats is, ",mean_rmse_spline_5*100,"%\n\n")
mean_ioa_spline_5 = mean(ioa_spline_5_zoo)
cat("Mean IOA for na.spline method with Gap Value of 5 is ",mean_ioa_spline_5, "thats is, ",mean_ioa_spline_5*100,"%\n\n")
mean_mad_spline_5 = mean(mad_spline_5_zoo)
cat("Mean MAD for na.spline method with Gap Value of 5 is ",mean_mad_spline_5,"\n\n")
mad_spline_zoo = c(mad_spline_zoo,mean_mad_spline_5)
frac_bias_spline_zoo = c(frac_bias_spline_zoo,mean_fractional_bias_spline_5)
rmse_spline_zoo = c(rmse_spline_zoo,mean_rmse_spline_5)
ioa_spline_zoo = c(ioa_spline_zoo, mean_ioa_spline_5)
rm(temp1)
rm(temp2)
rm(temp3)
rm(temp4)
rm(x)
rm(i)
rm(j)
```

###########################################################################################################

Method = {zoo}na.spline
Gap = 10

Pre-dia "2133-017"
Method = {zoo}na.spline
```{r}
pre_dia = subset(series, series[,3] == "2133-017")
```


```{r}
mad_spline_10_zoo = c()
fractional_bias_spline_10_zoo = c()
rmse_spline_10_zoo = c()
ioa_spline_10_zoo = c()
```

```{r}
for (i in seed_points) { 
  series_new = pre_dia
  for (j in 0:9) { 
    series_new$GlucoseValue[i+j] = NA
  }
  series_new$GlucoseValue = na.spline(unfactor(series_new$GlucoseValue))
    
  #calculating mean absolute difference
  temp1 = mad(series_new$GlucoseValue)
  mad_spline_10_zoo = c(mad_spline_10_zoo,temp1)
    
  #calculating fractional bias
  temp2 = compute.fb(series_new$GlucoseValue, unfactor(pre_dia$GlucoseValue))
  fractional_bias_spline_10_zoo = c(fractional_bias_spline_10_zoo, temp2)
    
  #calculating RMSE
  temp3 = compute.rmse(series_new$GlucoseValue, unfactor(pre_dia$GlucoseValue))
  rmse_spline_10_zoo = c(rmse_spline_10_zoo,temp3)
  
  #calculatind IOA
  x = data.frame("real" = unfactor(pre_dia$GlucoseValue), 'imputed' = series_new$GlucoseValue)
  temp4 = modStats(x,mod = "imputed",obs = "real", statistic = c("IOA"))
  ioa_spline_10_zoo = c(ioa_spline_10_zoo, temp4$IOA)
}
```

```{r}
mean_fractional_bias_spline_10 = mean(fractional_bias_spline_10_zoo)
cat("Mean Fractional Bias for na.spline method with Gap Value of 10 is ",mean_fractional_bias_spline_10, "thats is, ",mean_fractional_bias_spline_10*100,"%\n\n")
mean_rmse_spline_10 = mean(rmse_spline_10_zoo)
cat("Mean RMSE for na.spline method with Gap Value of 10 is ",mean_rmse_spline_10, "thats is, ",mean_rmse_spline_10*100,"%\n\n")
mean_ioa_spline_10 = mean(ioa_spline_10_zoo)
cat("Mean IOA for na.spline method with Gap Value of 10 is ",mean_ioa_spline_10, "thats is, ",mean_ioa_spline_10*100,"%\n\n")
mean_mad_spline_10 = mean(mad_spline_10_zoo)
cat("Mean MAD for na.spline method with Gap Value of 10 is ",mean_mad_spline_10,"\n\n")
mad_spline_zoo = c(mad_spline_zoo,mean_mad_spline_10)
frac_bias_spline_zoo = c(frac_bias_spline_zoo,mean_fractional_bias_spline_10)
rmse_spline_zoo = c(rmse_spline_zoo,mean_rmse_spline_10)
ioa_spline_zoo = c(ioa_spline_zoo, mean_ioa_spline_10)
rm(temp1)
rm(temp2)
rm(temp3)
rm(temp4)
rm(x)
rm(i)
rm(j)
```

###########################################################################################################

Method = {zoo}na.spline
Gap = 20

Pre-dia "2133-017"
Method = {zoo}na.spline
```{r}
pre_dia = subset(series, series[,3] == "2133-017")
```


```{r}
mad_spline_20_zoo = c()
fractional_bias_spline_20_zoo = c()
rmse_spline_20_zoo = c()
ioa_spline_20_zoo = c()
```

```{r}
for (i in seed_points) { 
  series_new = pre_dia
  for (j in 0:19) { 
    series_new$GlucoseValue[i+j] = NA
  }
  series_new$GlucoseValue = na.spline(unfactor(series_new$GlucoseValue))
    
  #calculating mean absolute difference
  temp1 = mad(series_new$GlucoseValue)
  mad_spline_20_zoo = c(mad_spline_20_zoo,temp1)
    
  #calculating fractional bias
  temp2 = compute.fb(series_new$GlucoseValue, unfactor(pre_dia$GlucoseValue))
  fractional_bias_spline_20_zoo = c(fractional_bias_spline_20_zoo, temp2)
    
  #calculating RMSE
  temp3 = compute.rmse(series_new$GlucoseValue, unfactor(pre_dia$GlucoseValue))
  rmse_spline_20_zoo = c(rmse_spline_20_zoo,temp3)
  
  #calculatind IOA
  x = data.frame("real" = unfactor(pre_dia$GlucoseValue), 'imputed' = series_new$GlucoseValue)
  temp4 = modStats(x,mod = "imputed",obs = "real", statistic = c("IOA"))
  ioa_spline_20_zoo = c(ioa_spline_20_zoo, temp4$IOA)
}
```

```{r}
mean_fractional_bias_spline_20 = mean(fractional_bias_spline_20_zoo)
cat("Mean Fractional Bias for na.spline method with Gap Value of 20 is ",mean_fractional_bias_spline_20, "thats is, ",mean_fractional_bias_spline_20*100,"%\n\n")
mean_rmse_spline_20 = mean(rmse_spline_20_zoo)
cat("Mean RMSE for na.spline method with Gap Value of 20 is ",mean_rmse_spline_20, "thats is, ",mean_rmse_spline_20*100,"%\n\n")
mean_ioa_spline_20 = mean(ioa_spline_20_zoo)
cat("Mean IOA for na.spline method with Gap Value of 20 is ",mean_ioa_spline_20, "thats is, ",mean_ioa_spline_20*100,"%\n\n")
mean_mad_spline_20 = mean(mad_spline_20_zoo)
cat("Mean MAD for na.spline method with Gap Value of 20 is ",mean_mad_spline_20,"\n\n")
mad_spline_zoo = c(mad_spline_zoo,mean_mad_spline_20)
frac_bias_spline_zoo = c(frac_bias_spline_zoo,mean_fractional_bias_spline_20)
rmse_spline_zoo = c(rmse_spline_zoo,mean_rmse_spline_20)
ioa_spline_zoo = c(ioa_spline_zoo, mean_ioa_spline_20)
rm(temp1)
rm(temp2)
rm(temp3)
rm(temp4)
rm(x)
rm(i)
rm(j)
```

###########################################################################################################

Method = {zoo}na.spline
Gap = 25

Pre-dia "2133-017"
Method = {zoo}na.spline
```{r}
pre_dia = subset(series, series[,3] == "2133-017")
```


```{r}
mad_spline_25_zoo = c()
fractional_bias_spline_25_zoo = c()
rmse_spline_25_zoo = c()
ioa_spline_25_zoo = c()
```

```{r}
for (i in seed_points) { 
  series_new = pre_dia
  for (j in 0:24) { 
    series_new$GlucoseValue[i+j] = NA
  }
  series_new$GlucoseValue = na.spline(unfactor(series_new$GlucoseValue))
    
  #calculating mean absolute difference
  temp1 = mad(series_new$GlucoseValue)
  mad_spline_25_zoo = c(mad_spline_25_zoo,temp1)
    
  #calculating fractional bias
  temp2 = compute.fb(series_new$GlucoseValue, unfactor(pre_dia$GlucoseValue))
  fractional_bias_spline_25_zoo = c(fractional_bias_spline_25_zoo, temp2)
    
  #calculating RMSE
  temp3 = compute.rmse(series_new$GlucoseValue, unfactor(pre_dia$GlucoseValue))
  rmse_spline_25_zoo = c(rmse_spline_25_zoo,temp3)
  
  #calculatind IOA
  x = data.frame("real" = unfactor(pre_dia$GlucoseValue), 'imputed' = series_new$GlucoseValue)
  temp4 = modStats(x,mod = "imputed",obs = "real", statistic = c("IOA"))
  ioa_spline_25_zoo = c(ioa_spline_25_zoo, temp4$IOA)
}
```

```{r}
mean_fractional_bias_spline_25 = mean(fractional_bias_spline_25_zoo)
cat("Mean Fractional Bias for na.spline method with Gap Value of 25 is ",mean_fractional_bias_spline_25, "thats is, ",mean_fractional_bias_spline_25*100,"%\n\n")
mean_rmse_spline_25 = mean(rmse_spline_25_zoo)
cat("Mean RMSE for na.spline method with Gap Value of 25 is ",mean_rmse_spline_25, "thats is, ",mean_rmse_spline_25*100,"%\n\n")
mean_ioa_spline_25 = mean(ioa_spline_25_zoo)
cat("Mean IOA for na.spline method with Gap Value of 25 is ",mean_ioa_spline_25, "thats is, ",mean_ioa_spline_25*100,"%\n\n")
mean_mad_spline_25 = mean(mad_spline_25_zoo)
cat("Mean MAD for na.spline method with Gap Value of 25 is ",mean_mad_spline_25,"\n\n")
mad_spline_zoo = c(mad_spline_zoo,mean_mad_spline_25)
frac_bias_spline_zoo = c(frac_bias_spline_zoo,mean_fractional_bias_spline_25)
rmse_spline_zoo = c(rmse_spline_zoo,mean_rmse_spline_25)
ioa_spline_zoo = c(ioa_spline_zoo, mean_ioa_spline_25)
rm(temp1)
rm(temp2)
rm(temp3)
rm(temp4)
rm(x)
rm(i)
rm(j)
```


###########################################################################################################

Method = {zoo}na.spline
Gap = 50

Pre-dia "2133-017"
Method = {zoo}na.spline
```{r}
pre_dia = subset(series, series[,3] == "2133-017")
```


```{r}
mad_spline_50_zoo = c()
fractional_bias_spline_50_zoo = c()
rmse_spline_50_zoo = c()
ioa_spline_50_zoo = c()
```

```{r}
for (i in seed_points) { 
  series_new = pre_dia
  for (j in 0:49) { 
    series_new$GlucoseValue[i+j] = NA
  }
  series_new$GlucoseValue = na.spline(unfactor(series_new$GlucoseValue))
    
  #calculating mean absolute difference
  temp1 = mad(series_new$GlucoseValue)
  mad_spline_50_zoo = c(mad_spline_50_zoo,temp1)
    
  #calculating fractional bias
  temp2 = compute.fb(series_new$GlucoseValue, unfactor(pre_dia$GlucoseValue))
  fractional_bias_spline_50_zoo = c(fractional_bias_spline_50_zoo, temp2)
    
  #calculating RMSE
  temp3 = compute.rmse(series_new$GlucoseValue, unfactor(pre_dia$GlucoseValue))
  rmse_spline_50_zoo = c(rmse_spline_50_zoo,temp3)
  
  #calculatind IOA
  x = data.frame("real" = unfactor(pre_dia$GlucoseValue), 'imputed' = series_new$GlucoseValue)
  temp4 = modStats(x,mod = "imputed",obs = "real", statistic = c("IOA"))
  ioa_spline_50_zoo = c(ioa_spline_50_zoo, temp4$IOA)
}
```

```{r}
mean_fractional_bias_spline_50 = mean(fractional_bias_spline_50_zoo)
cat("Mean Fractional Bias for na.spline method with Gap Value of 50 is ",mean_fractional_bias_spline_50, "thats is, ",mean_fractional_bias_spline_50*100,"%\n\n")
mean_rmse_spline_50 = mean(rmse_spline_50_zoo)
cat("Mean RMSE for na.spline method with Gap Value of 50 is ",mean_rmse_spline_50, "thats is, ",mean_rmse_spline_50*100,"%\n\n")
mean_ioa_spline_50 = mean(ioa_spline_50_zoo)
cat("Mean IOA for na.spline method with Gap Value of 50 is ",mean_ioa_spline_50, "thats is, ",mean_ioa_spline_50*100,"%\n\n")
mean_mad_spline_50 = mean(mad_spline_50_zoo)
cat("Mean MAD for na.spline method with Gap Value of 50 is ",mean_mad_spline_50,"\n\n")
mad_spline_zoo = c(mad_spline_zoo,mean_mad_spline_50)
frac_bias_spline_zoo = c(frac_bias_spline_zoo,mean_fractional_bias_spline_50)
rmse_spline_zoo = c(rmse_spline_zoo,mean_rmse_spline_50)
ioa_spline_zoo = c(ioa_spline_zoo, mean_ioa_spline_50)
rm(temp1)
rm(temp2)
rm(temp3)
rm(temp4)
rm(x)
rm(i)
rm(j)
```


###########################################################################################################

Method = {zoo}na.spline
Gap = 100

Pre-dia "2133-017"
Method = {zoo}na.spline
```{r}
pre_dia = subset(series, series[,3] == "2133-017")
```


```{r}
mad_spline_100_zoo = c()
fractional_bias_spline_100_zoo = c()
rmse_spline_100_zoo = c()
ioa_spline_100_zoo = c()
```

```{r}
for (i in seed_points) { 
  series_new = pre_dia
  for (j in 0:99) { 
    series_new$GlucoseValue[i+j] = NA
  }
  series_new$GlucoseValue = na.spline(unfactor(series_new$GlucoseValue))
    
  #calculating mean absolute difference
  temp1 = mad(series_new$GlucoseValue)
  mad_spline_100_zoo = c(mad_spline_100_zoo,temp1)
    
  #calculating fractional bias
  temp2 = compute.fb(series_new$GlucoseValue, unfactor(pre_dia$GlucoseValue))
  fractional_bias_spline_100_zoo = c(fractional_bias_spline_100_zoo, temp2)
    
  #calculating RMSE
  temp3 = compute.rmse(series_new$GlucoseValue, unfactor(pre_dia$GlucoseValue))
  rmse_spline_100_zoo = c(rmse_spline_100_zoo,temp3)
  
  #calculatind IOA
  x = data.frame("real" = unfactor(pre_dia$GlucoseValue), 'imputed' = series_new$GlucoseValue)
  temp4 = modStats(x,mod = "imputed",obs = "real", statistic = c("IOA"))
  ioa_spline_100_zoo = c(ioa_spline_100_zoo, temp4$IOA)
}
```

```{r}
mean_fractional_bias_spline_100 = mean(fractional_bias_spline_100_zoo)
cat("Mean Fractional Bias for na.spline method with Gap Value of 100 is ",mean_fractional_bias_spline_100, "thats is, ",mean_fractional_bias_spline_100*100,"%\n\n")
mean_rmse_spline_100 = mean(rmse_spline_100_zoo)
cat("Mean RMSE for na.spline method with Gap Value of 100 is ",mean_rmse_spline_100, "thats is, ",mean_rmse_spline_100*100,"%\n\n")
mean_ioa_spline_100 = mean(ioa_spline_100_zoo)
cat("Mean IOA for na.spline method with Gap Value of 100 is ",mean_ioa_spline_100, "thats is, ",mean_ioa_spline_100*100,"%\n\n")
mean_mad_spline_100 = mean(mad_spline_100_zoo)
cat("Mean MAD for na.spline method with Gap Value of 100 is ",mean_mad_spline_100,"\n\n")
mad_spline_zoo = c(mad_spline_zoo,mean_mad_spline_100)
frac_bias_spline_zoo = c(frac_bias_spline_zoo,mean_fractional_bias_spline_100)
rmse_spline_zoo = c(rmse_spline_zoo,mean_rmse_spline_100)
ioa_spline_zoo = c(ioa_spline_zoo, mean_ioa_spline_100)
rm(temp1)
rm(temp2)
rm(temp3)
rm(temp4)
rm(x)
rm(i)
rm(j)
```

na.spline final values
```{r}
mad_spline_zoo
frac_bias_spline_zoo
rmse_spline_zoo
ioa_spline_zoo
```
