---
title: "GVI_table"
author: "Sophia Ding"
date: "6/24/2020"
output: html_document
---
```{r}
#install.packages('devtools')
library(devtools)
install_github("MRCIEU/GLU")
```

```{r}
library(GLU)
library(lubridate)
library(varhandle)
library("openxlsx")
```

```{r}
indir='/Users/yuxiding/Desktop/GLU-master/inst/extdata/freestyle-libre/original'
outdir='/Users/yuxiding/Desktop'
runGLUForDirectory(indir, outdir, device=2, freq=5)
```

```{r}
datadir=system.file("extdata", package = "GLU")
runGLUForDirectory(indir='/Users/yuxiding/Desktop/GLU-master/inst/extdata/dexcom-g6/original', outdir='/Users/yuxiding/Desktop/aa', device=1, nightstart='16:00', imputeOther=TRUE)
```


```{r setup, include=FALSE}
dataset <- read.delim("~/Desktop/dataset.s010")
dataset 
```
```{r}
dataset$day <- as.Date(dataset$DisplayTime)
dataset
```
```{r}
pre = subset(dataset, dataset$subjectId == "1636-69-032")
pre$day = as.character(pre$day)
d = c('2016-01-14', '2016-01-15', '2016-01-16', '2016-01-17', '2016-01-18')
prediabetic  = pre[pre$day %in% d,]

prediabetic$DisplayTime = unfactor(prediabetic$DisplayTime)
prediabetic$GlucoseValue = unfactor(prediabetic$GlucoseValue)
t = strptime(prediabetic$DisplayTime, format = '%Y-%m-%d %H:%M:%S')

#prediabetic$min = format(t,  '%H:%M:%S')

#prediabetic$GlucoseValue = round(prediabetic$GlucoseValue / 18, digits = 2)
prediabetic$GlucoseValue = prediabetic$GlucoseValue / 18

#prediabetic$time <- gsub(" ", "T", prediabetic$DisplayTime)

timeFormat = '%Y-%m-%dT%H:%M:%S'
#prediabetic$time = strptime(data$time, format=timeFormat)
prediabetic$time = format(t, timeFormat)

prediabetic
write.xlsx(prediabetic,file = "~/Desktop/prediabetic_reformat.xlsx")
```
```{r}
prediabetic_reformat = prediabetic[,1:2]
colnames(prediabetic_reformat) = c('time', 'sgReading')
#prediabetic_reformat$time = as.POSIXct(prediabetic_reformat$time)

prediabetic_reformat$time <- as.POSIXct(prediabetic_reformat$time, format = '%d/%m/%Y %H:%M:%S')    

prediabetic_reformat

#write.xlsx(prediabetic_reformat,file = "~/Desktop/prediabetic_reformat.xlsx")

```



```{r}
library('GLU')

#runGLUForDirectory(indir='/Users/yuxiding/Desktop/GLU-master/inst/extdata/dexcom-g6/original', outdir='/Users/yuxiding/Desktop/GLU-output', device=2, imputeapproximal=TRUE, freq=5, nightstart='00:00')

runGLUForDirectory(indir='/Users/yuxiding/Desktop/GLU-master/inst/extdata/dexcom-g6/original', outdir='/Users/yuxiding/Desktop/GLU-output', device=1, freq=5, nightstart='00:00', imputeOther=FALSE)
#device=1, nightstart='16:00', imputeOther=TRUE)

```
