---
title: "CGManalyzer"
author: "Sophia Ding"
date: "6/25/2020"
output: html_document
---
```{r}
dataset <- read.delim("~/Desktop/dataset.s010")

dataset$day <- as.Date(dataset$DisplayTime)

pre = subset(dataset, dataset$subjectId == "1636-69-032")
pre$day = as.character(pre$day)
d = c('2016-01-14', '2016-01-15', '2016-01-16', '2016-01-17', '2016-01-18')
prediabetic  = pre[pre$day %in% d,]

prediabetic$DisplayTime = unfactor(prediabetic$DisplayTime)
prediabetic$GlucoseValue = unfactor(prediabetic$GlucoseValue)
t = strptime(prediabetic$DisplayTime, format = '%Y-%m-%d %H:%M:%S')
prediabetic$DisplayTime = format(t,  '%Y:%m:%d %H:%M:%S')

prediabetic_reformat = prediabetic[,1:2]
colnames(prediabetic_reformat) = c('timeStamp', 'glucoseValue')

prediabetic_reformat

#write.csv(prediabetic_reformat,file = "~/Desktop/prediabetic_reformat.csv")
```
```{r}
MODD.fn <- function(y, Interval = 5) {
#***************************************************************************
# Function to calculate the mean of daily differences (MODD). 
# MODD:
#   The absolute value of the difference between glucose values taken
#   on two consecutive days at the same time was calculated; the MODD is 
#   the mean of these differences.
# Input 
#   y: measured response, must be evenly spaced in measured time
#   Interval: number of minutes between two consecutive time points
# Output
#   a value of MODD
# Author: Xiaohua Douglas Zhang
# Date:   2017-12-12
#****************************************************************************

	Nsegment <- floor(length(y)*Interval/24)
	Npoint <- 24/Interval
	if( Nsegment < 2) {
		MODD <- NA
	    warning("To be able to calculate MODD, the number of full days must be at least 2!")
	} else {
		diff.mat <- matrix( NA, nrow=Nsegment-1, ncol= Npoint)
		for( i in 1:(Nsegment-1) ) {
				diff.mat[i, ] <- y[i*Npoint+1:Npoint] - y[(i-1)*Npoint+1:Npoint] 
		}
		MODD <- mean( abs(as.vector(diff.mat)), na.rm=TRUE )	
	}
	return( MODD )
}
```

```{r}
MODD.fn(prediabetic_reformat$glucoseValue)
```
```{r}
CONGA.fn <- function(y, Interval = 5, n=2) {
#***************************************************************************
# Function to calculate the continuous overlapping net glycemic action (CONGA). 
# CONGA:  
#  For each observation after the first n hours of observations, the difference 
#  between the current observation and the observation n hours previous was calculated. 
#  CONGAn is defined as the standard deviation of the differences.
# Input 
#   y: measured response, must be evenly spaced in measured time
#   Interval: number of minutes between two consecutive time points
#   n: the length of a segment in CONGA 
# Output
#   a value of CONGA
# Author: Xiaohua Douglas Zhang, Dandan Wang
# Date:   2017-12-12
#****************************************************************************

	Npoint.segment <- 60/Interval*n
	N <- length(y)-Npoint.segment
	diff.vec <- rep(NA, N)
	for( i in 1:N ) {
		diff.vec[i] <- y[i+Npoint.segment] - y[i]
	}
	CONGA <- sd( diff.vec, na.rm=TRUE)
	return(CONGA)
}
```

```{r}
CONGA.fn(prediabetic_reformat$glucoseValue, Interval = 5, n=4)
```

```{r}
MSEbyC.fn <-
function(x, scaleMax=10, scaleStep=1, mMin=2, mMax=2, mStep=1, rMin=0.15, rMax=0.15,
		 I=400000)
{
# **********************************************************************************
# Function to call and run a C program to calculate multiscale entropy (MSE)
#     of an equally spaced time series.
#
# ARGUMENTS
#  x: A numeric vector, with data for a regularly spaced time series.
#     No missing value is allowed because the C program is not set up to
#     handle missing value.
#  scaleMax: maximal value of scale factors for coarse graining in the MSE algorithm.
#     The scale factors are a sequence from 1 to a value no more than 'scaleMax'
#     with equal space 'scaleStep'.  Scale factors are positive integers that specify
#     bin size for coarse graining: the number of consecutive observations
#     in 'x' that form a bin and are averaged in the first step of the algorithm.
#  scaleStep: see 'scaleMax' above.
#  mMin: A sequence from 'mMin' to 'mMax' with equal space of 'mStep' that defines
#     the vector of positive integers that give the window size for the entropy
#     calculations in the second step of the algorithm:  the number of
#     consecutive _bins_ over which similarity between subsequences is
#     of interest.  Typical values in the sequence are 1, 2, or 3.
#  mMax and mStep: See 'Min' above
#  rMin and rMax: A sequence from 'rMin' to 'rMax' with equal space of 0.05 that defines
#     coefficients for similarity thresholds. Typical values in the sequence are 0.15, 0.2.
#     r*sd(x) must be in the same units as 'x'. Averages in two bins are
#     defined to be similar if they differ by 'r*sd(x)' or less.
#  I: the maximal number of points to be used for calculating MSE
# VALUE
#  A data frame with with one row for each combination of 'Scale', 'm' and 'rSD'.
#  Columns are "Scale", "m", "rSD", and "SampEn" (the calculated sample entropy).
#  The data frame will also have an attribute "SD", the standard deviation
#  of 'x'. rSD = r*sd(x)

# VERSION
#  V1:  X.H.D. Zhang, July 3, 2017
#*******************************************************************************************

  if ( anyNA(x) )  stop("'NA' values in 'x' are not allowed")
  N <- length(x)
  if ( scaleMax > N/10 )  stop( "'Scale' is too large compared to data length" )

  # Temporary files for input and output for running a C program
  tempin <- tempfile("tempin", tmpdir=getwd(), fileext=".txt")
  tempout <- tempfile("tempout", tmpdir=getwd(), fileext=".txt")
  write(x, file=tempin, ncolumns=1, sep="\t")
  on.exit(unlink(tempin))

  # only for test
  # mMin <- 0
  options(scipen=999)
  # Construct command line arguments for running the C program.
  Args <- paste("-n", scaleMax, "-a", scaleStep, "-b", mStep, "-m", mMin, "-M", mMax,
               "-r", rMin, "-R", rMax, "-I", I)


  #Command <- paste0(cFolder, "/", cmdCore, ".e","xe")
  cmd <- paste("MSE.exe", Args, "-z", tempin, "-Z", tempout)
  on.exit(unlink(tempout), add=TRUE)
  #shell(cmd, wait=TRUE, intern=FALSE, invisible=TRUE)
  # Call the C function 'Mse' to calculate sample entropy
  .C(C_Mse, cmd)

  # Read calculated sample entropy back into R
  Text <- readLines(tempout)
  Text <- Text[-(1:4)]                		    # exclude 4 header lines
  Text <- Text[Text != ""]            			# exclude empty line
  blockStarts <- grep("^m =", Text)	            # identify block start line "m = ,  r = "
  blockEnds <- c(tail(blockStarts, -1) - 1, length(Text))
  result.lst <- vector("list", length(blockStarts))
  for (i in seq_along(blockStarts)) {
    blockLine1 <- Text[ blockStarts[i] ]
    mr.vec <- eval(parse(text=paste0("c(", blockLine1, ")")))
    con <- textConnection(Text[(blockStarts[i]+1):(blockEnds[i])])
    mseBlock.df <- read.table(con, header=FALSE, sep="\t", row.names=NULL,
							  col.names=c("Scale", "SampleEntropy", "endNA"),
							  colClasses="numeric", comment.char="")
    mseBlock.df$endNA <- NULL  # remove the last NA column generated by trailing "\t" in each line
    close(con)
    result.lst[[i]] <- data.frame("m"=rep(mr.vec["m"], nrow(mseBlock.df)),
                            "r"=rep(mr.vec["r"], nrow(mseBlock.df)), mseBlock.df)
  }
  # Combine results in all block into a single data frame.
  result.df <- do.call("rbind", result.lst)
}

```
```{r}
MSEbyC.fn(prediabetic_reformat$glucoseValue)
```

