---
title: "R Notebook"
output: html_notebook
---
```{r}
series <- read.delim("~/Desktop/dataset.s010")
series = na.omit(series)
library(varhandle)
library(imputeTS)
library(zoo)
library(DTWBI)
library(openair)
```
Dia 
na.spline error lists for plotting
```{r}
mad_spline_imputeTS = c()
frac_bias_spline_imputeTS = c()
rmse_spline_imputeTS = c()
ioa_spline_imputeTS = c()
```

Dia "2133-018"
Method = {imputeTS} spline
```{r}
dia = subset(series, series[,3] == "2133-018")
```

Gap = 5
```{r}
mad_spline_5_imputeTS = c()
fractional_bias_spline_5_imputeTS = c()
rmse_spline_5_imputeTS = c()
ioa_spline_5_imputeTS = c()
```

```{r}
seed_points <- sample(1:1500, 100, replace = FALSE)
```

```{r}
for (i in seed_points) { 
  series_new = dia
  for (j in 0:4) { 
    series_new$GlucoseValue[i+j] = NA
  }
  series_new$GlucoseValue = na_interpolation(unfactor(series_new$GlucoseValue), option = "spline", maxgap = Inf)
    
  #calculating mean absolute difference
  temp1 = mad(series_new$GlucoseValue)
  mad_spline_5_imputeTS = c(mad_spline_5_imputeTS,temp1)
    
  #calculating fractional bias
  temp2 = compute.fb(series_new$GlucoseValue, unfactor(dia$GlucoseValue))
  fractional_bias_spline_5_imputeTS = c(fractional_bias_spline_5_imputeTS, temp2)
    
  #calculating RMSE
  temp3 = compute.rmse(series_new$GlucoseValue, unfactor(dia$GlucoseValue))
  rmse_spline_5_imputeTS = c(rmse_spline_5_imputeTS,temp3)
  
  #calculatind IOA
  x = data.frame("real" = unfactor(dia$GlucoseValue), 'imputed' = series_new$GlucoseValue)
  temp4 = modStats(x,mod = "imputed",obs = "real", statistic = c("IOA"))
  ioa_spline_5_imputeTS = c(ioa_spline_5_imputeTS, temp4$IOA)
}
```
 
```{r}
mean_fractional_bias_spline_5 = mean(fractional_bias_spline_5_imputeTS)
cat("Mean Fractional Bias for na.spline method with Gap Value of 5 is ",mean_fractional_bias_spline_5, "thats is, ",mean_fractional_bias_spline_5*100,"%\n\n")
mean_rmse_spline_5 = mean(rmse_spline_5_imputeTS)
cat("Mean RMSE for na.spline method with Gap Value of 5 is ",mean_rmse_spline_5, "thats is, ",mean_rmse_spline_5*100,"%\n\n")
mean_ioa_spline_5 = mean(ioa_spline_5_imputeTS)
cat("Mean IOA for na.spline method with Gap Value of 5 is ",mean_ioa_spline_5, "thats is, ",mean_ioa_spline_5*100,"%\n\n")
mean_mad_spline_5 = mean(mad_spline_5_imputeTS)
cat("Mean MAD for na.spline method with Gap Value of 5 is ",mean_mad_spline_5,"\n\n")
mad_spline_imputeTS = c(mad_spline_imputeTS,mean_mad_spline_5)
frac_bias_spline_imputeTS = c(frac_bias_spline_imputeTS,mean_fractional_bias_spline_5)
rmse_spline_imputeTS = c(rmse_spline_imputeTS,mean_rmse_spline_5)
ioa_spline_imputeTS = c(ioa_spline_imputeTS, mean_ioa_spline_5)
rm(temp1)
rm(temp2)
rm(temp3)
rm(temp4)
rm(x)
rm(i)
rm(j)
```

###########################################################################################################

Method = {imputeTS} spline
Gap = 10

Dia "2133-018"
Method = {zoo}na.spline
```{r}
dia = subset(series, series[,3] == "2133-018")
```


```{r}
mad_spline_10_imputeTS = c()
fractional_bias_spline_10_imputeTS = c()
rmse_spline_10_imputeTS = c()
ioa_spline_10_imputeTS = c()
```

```{r}
for (i in seed_points) { 
  series_new = dia
  for (j in 0:9) { 
    series_new$GlucoseValue[i+j] = NA
  }
  series_new$GlucoseValue = na_interpolation(unfactor(series_new$GlucoseValue), option = "spline", maxgap = Inf)
    
  #calculating mean absolute difference
  temp1 = mad(series_new$GlucoseValue)
  mad_spline_10_imputeTS = c(mad_spline_10_imputeTS,temp1)
    
  #calculating fractional bias
  temp2 = compute.fb(series_new$GlucoseValue, unfactor(dia$GlucoseValue))
  fractional_bias_spline_10_imputeTS = c(fractional_bias_spline_10_imputeTS, temp2)
    
  #calculating RMSE
  temp3 = compute.rmse(series_new$GlucoseValue, unfactor(dia$GlucoseValue))
  rmse_spline_10_imputeTS = c(rmse_spline_10_imputeTS,temp3)
  
  #calculatind IOA
  x = data.frame("real" = unfactor(dia$GlucoseValue), 'imputed' = series_new$GlucoseValue)
  temp4 = modStats(x,mod = "imputed",obs = "real", statistic = c("IOA"))
  ioa_spline_10_imputeTS = c(ioa_spline_10_imputeTS, temp4$IOA)
}
```

```{r}
mean_fractional_bias_spline_10 = mean(fractional_bias_spline_10_imputeTS)
cat("Mean Fractional Bias for na.spline method with Gap Value of 10 is ",mean_fractional_bias_spline_10, "thats is, ",mean_fractional_bias_spline_10*100,"%\n\n")
mean_rmse_spline_10 = mean(rmse_spline_10_imputeTS)
cat("Mean RMSE for na.spline method with Gap Value of 10 is ",mean_rmse_spline_10, "thats is, ",mean_rmse_spline_10*100,"%\n\n")
mean_ioa_spline_10 = mean(ioa_spline_10_imputeTS)
cat("Mean IOA for na.spline method with Gap Value of 10 is ",mean_ioa_spline_10, "thats is, ",mean_ioa_spline_10*100,"%\n\n")
mean_mad_spline_10 = mean(mad_spline_10_imputeTS)
cat("Mean MAD for na.spline method with Gap Value of 10 is ",mean_mad_spline_10,"\n\n")
mad_spline_imputeTS = c(mad_spline_imputeTS,mean_mad_spline_10)
frac_bias_spline_imputeTS = c(frac_bias_spline_imputeTS,mean_fractional_bias_spline_10)
rmse_spline_imputeTS = c(rmse_spline_imputeTS,mean_rmse_spline_10)
ioa_spline_imputeTS = c(ioa_spline_imputeTS, mean_ioa_spline_10)
rm(temp1)
rm(temp2)
rm(temp3)
rm(temp4)
rm(x)
rm(i)
rm(j)
```

###########################################################################################################

Method = {imputeTS} spline
Gap = 20
Dia "2133-018"

```{r}
dia = subset(series, series[,3] == "2133-018")
```


```{r}
mad_spline_20_imputeTS = c()
fractional_bias_spline_20_imputeTS = c()
rmse_spline_20_imputeTS = c()
ioa_spline_20_imputeTS = c()
```

```{r}
for (i in seed_points) { 
  series_new = dia
  for (j in 0:19) { 
    series_new$GlucoseValue[i+j] = NA
  }
  series_new$GlucoseValue = na_interpolation(unfactor(series_new$GlucoseValue), option = "spline", maxgap = Inf)
    
  #calculating mean absolute difference
  temp1 = mad(series_new$GlucoseValue)
  mad_spline_20_imputeTS = c(mad_spline_20_imputeTS,temp1)
    
  #calculating fractional bias
  temp2 = compute.fb(series_new$GlucoseValue, unfactor(dia$GlucoseValue))
  fractional_bias_spline_20_imputeTS = c(fractional_bias_spline_20_imputeTS, temp2)
    
  #calculating RMSE
  temp3 = compute.rmse(series_new$GlucoseValue, unfactor(dia$GlucoseValue))
  rmse_spline_20_imputeTS = c(rmse_spline_20_imputeTS,temp3)
  
  #calculatind IOA
  x = data.frame("real" = unfactor(dia$GlucoseValue), 'imputed' = series_new$GlucoseValue)
  temp4 = modStats(x,mod = "imputed",obs = "real", statistic = c("IOA"))
  ioa_spline_20_imputeTS = c(ioa_spline_20_imputeTS, temp4$IOA)
}
```

```{r}
mean_fractional_bias_spline_20 = mean(fractional_bias_spline_20_imputeTS)
cat("Mean Fractional Bias for na.spline method with Gap Value of 20 is ",mean_fractional_bias_spline_20, "thats is, ",mean_fractional_bias_spline_20*100,"%\n\n")
mean_rmse_spline_20 = mean(rmse_spline_20_imputeTS)
cat("Mean RMSE for na.spline method with Gap Value of 20 is ",mean_rmse_spline_20, "thats is, ",mean_rmse_spline_20*100,"%\n\n")
mean_ioa_spline_20 = mean(ioa_spline_20_imputeTS)
cat("Mean IOA for na.spline method with Gap Value of 20 is ",mean_ioa_spline_20, "thats is, ",mean_ioa_spline_20*100,"%\n\n")
mean_mad_spline_20 = mean(mad_spline_20_imputeTS)
cat("Mean MAD for na.spline method with Gap Value of 20 is ",mean_mad_spline_20,"\n\n")
mad_spline_imputeTS = c(mad_spline_imputeTS,mean_mad_spline_20)
frac_bias_spline_imputeTS = c(frac_bias_spline_imputeTS,mean_fractional_bias_spline_20)
rmse_spline_imputeTS = c(rmse_spline_imputeTS,mean_rmse_spline_20)
ioa_spline_imputeTS = c(ioa_spline_imputeTS, mean_ioa_spline_20)
rm(temp1)
rm(temp2)
rm(temp3)
rm(temp4)
rm(x)
rm(i)
rm(j)
```

###########################################################################################################

Method = {imputeTS} spline
Gap = 25
Dia "2133-018"

```{r}
dia = subset(series, series[,3] == "2133-018")
```


```{r}
mad_spline_25_imputeTS = c()
fractional_bias_spline_25_imputeTS = c()
rmse_spline_25_imputeTS = c()
ioa_spline_25_imputeTS = c()
```

```{r}
for (i in seed_points) { 
  series_new = dia
  for (j in 0:24) { 
    series_new$GlucoseValue[i+j] = NA
  }
  series_new$GlucoseValue = na_interpolation(unfactor(series_new$GlucoseValue), option = "spline", maxgap = Inf)
    
  #calculating mean absolute difference
  temp1 = mad(series_new$GlucoseValue)
  mad_spline_25_imputeTS = c(mad_spline_25_imputeTS,temp1)
    
  #calculating fractional bias
  temp2 = compute.fb(series_new$GlucoseValue, unfactor(dia$GlucoseValue))
  fractional_bias_spline_25_imputeTS = c(fractional_bias_spline_25_imputeTS, temp2)
    
  #calculating RMSE
  temp3 = compute.rmse(series_new$GlucoseValue, unfactor(dia$GlucoseValue))
  rmse_spline_25_imputeTS = c(rmse_spline_25_imputeTS,temp3)
  
  #calculatind IOA
  x = data.frame("real" = unfactor(dia$GlucoseValue), 'imputed' = series_new$GlucoseValue)
  temp4 = modStats(x,mod = "imputed",obs = "real", statistic = c("IOA"))
  ioa_spline_25_imputeTS = c(ioa_spline_25_imputeTS, temp4$IOA)
}
```

```{r}
mean_fractional_bias_spline_25 = mean(fractional_bias_spline_25_imputeTS)
cat("Mean Fractional Bias for na.spline method with Gap Value of 25 is ",mean_fractional_bias_spline_25, "thats is, ",mean_fractional_bias_spline_25*100,"%\n\n")
mean_rmse_spline_25 = mean(rmse_spline_25_imputeTS)
cat("Mean RMSE for na.spline method with Gap Value of 25 is ",mean_rmse_spline_25, "thats is, ",mean_rmse_spline_25*100,"%\n\n")
mean_ioa_spline_25 = mean(ioa_spline_25_imputeTS)
cat("Mean IOA for na.spline method with Gap Value of 25 is ",mean_ioa_spline_25, "thats is, ",mean_ioa_spline_25*100,"%\n\n")
mean_mad_spline_25 = mean(mad_spline_25_imputeTS)
cat("Mean MAD for na.spline method with Gap Value of 25 is ",mean_mad_spline_25,"\n\n")
mad_spline_imputeTS = c(mad_spline_imputeTS,mean_mad_spline_25)
frac_bias_spline_imputeTS = c(frac_bias_spline_imputeTS,mean_fractional_bias_spline_25)
rmse_spline_imputeTS = c(rmse_spline_imputeTS,mean_rmse_spline_25)
ioa_spline_imputeTS = c(ioa_spline_imputeTS, mean_ioa_spline_25)
rm(temp1)
rm(temp2)
rm(temp3)
rm(temp4)
rm(x)
rm(i)
rm(j)
```


###########################################################################################################

Method = {imputeTS} spline
Gap = 50
Dia "2133-018"

```{r}
dia = subset(series, series[,3] == "2133-018")
```


```{r}
mad_spline_50_imputeTS = c()
fractional_bias_spline_50_imputeTS = c()
rmse_spline_50_imputeTS = c()
ioa_spline_50_imputeTS = c()
```

```{r}
for (i in seed_points) { 
  series_new = dia
  for (j in 0:49) { 
    series_new$GlucoseValue[i+j] = NA
  }
  series_new$GlucoseValue = na_interpolation(unfactor(series_new$GlucoseValue), option = "spline", maxgap = Inf)
    
  #calculating mean absolute difference
  temp1 = mad(series_new$GlucoseValue)
  mad_spline_50_imputeTS = c(mad_spline_50_imputeTS,temp1)
    
  #calculating fractional bias
  temp2 = compute.fb(series_new$GlucoseValue, unfactor(dia$GlucoseValue))
  fractional_bias_spline_50_imputeTS = c(fractional_bias_spline_50_imputeTS, temp2)
    
  #calculating RMSE
  temp3 = compute.rmse(series_new$GlucoseValue, unfactor(dia$GlucoseValue))
  rmse_spline_50_imputeTS = c(rmse_spline_50_imputeTS,temp3)
  
  #calculatind IOA
  x = data.frame("real" = unfactor(dia$GlucoseValue), 'imputed' = series_new$GlucoseValue)
  temp4 = modStats(x,mod = "imputed",obs = "real", statistic = c("IOA"))
  ioa_spline_50_imputeTS = c(ioa_spline_50_imputeTS, temp4$IOA)
}
```

```{r}
mean_fractional_bias_spline_50 = mean(fractional_bias_spline_50_imputeTS)
cat("Mean Fractional Bias for na.spline method with Gap Value of 50 is ",mean_fractional_bias_spline_50, "thats is, ",mean_fractional_bias_spline_50*100,"%\n\n")
mean_rmse_spline_50 = mean(rmse_spline_50_imputeTS)
cat("Mean RMSE for na.spline method with Gap Value of 50 is ",mean_rmse_spline_50, "thats is, ",mean_rmse_spline_50*100,"%\n\n")
mean_ioa_spline_50 = mean(ioa_spline_50_imputeTS)
cat("Mean IOA for na.spline method with Gap Value of 50 is ",mean_ioa_spline_50, "thats is, ",mean_ioa_spline_50*100,"%\n\n")
mean_mad_spline_50 = mean(mad_spline_50_imputeTS)
cat("Mean MAD for na.spline method with Gap Value of 50 is ",mean_mad_spline_50,"\n\n")
mad_spline_imputeTS = c(mad_spline_imputeTS,mean_mad_spline_50)
frac_bias_spline_imputeTS = c(frac_bias_spline_imputeTS,mean_fractional_bias_spline_50)
rmse_spline_imputeTS = c(rmse_spline_imputeTS,mean_rmse_spline_50)
ioa_spline_imputeTS = c(ioa_spline_imputeTS, mean_ioa_spline_50)
rm(temp1)
rm(temp2)
rm(temp3)
rm(temp4)
rm(x)
rm(i)
rm(j)
```


###########################################################################################################

Method = {imputeTS} spline
Gap = 100
Dia "2133-018"

```{r}
dia = subset(series, series[,3] == "2133-018")
```


```{r}
mad_spline_100_imputeTS = c()
fractional_bias_spline_100_imputeTS = c()
rmse_spline_100_imputeTS = c()
ioa_spline_100_imputeTS = c()
```

```{r}
for (i in seed_points) { 
  series_new = dia
  for (j in 0:99) { 
    series_new$GlucoseValue[i+j] = NA
  }
  series_new$GlucoseValue = na_interpolation(unfactor(series_new$GlucoseValue), option = "spline", maxgap = Inf)
    
  #calculating mean absolute difference
  temp1 = mad(series_new$GlucoseValue)
  mad_spline_100_imputeTS = c(mad_spline_100_imputeTS,temp1)
    
  #calculating fractional bias
  temp2 = compute.fb(series_new$GlucoseValue, unfactor(dia$GlucoseValue))
  fractional_bias_spline_100_imputeTS = c(fractional_bias_spline_100_imputeTS, temp2)
    
  #calculating RMSE
  temp3 = compute.rmse(series_new$GlucoseValue, unfactor(dia$GlucoseValue))
  rmse_spline_100_imputeTS = c(rmse_spline_100_imputeTS,temp3)
  
  #calculatind IOA
  x = data.frame("real" = unfactor(dia$GlucoseValue), 'imputed' = series_new$GlucoseValue)
  temp4 = modStats(x,mod = "imputed",obs = "real", statistic = c("IOA"))
  ioa_spline_100_imputeTS = c(ioa_spline_100_imputeTS, temp4$IOA)
}
```

```{r}
mean_fractional_bias_spline_100 = mean(fractional_bias_spline_100_imputeTS)
cat("Mean Fractional Bias for na.spline method with Gap Value of 100 is ",mean_fractional_bias_spline_100, "thats is, ",mean_fractional_bias_spline_100*100,"%\n\n")
mean_rmse_spline_100 = mean(rmse_spline_100_imputeTS)
cat("Mean RMSE for na.spline method with Gap Value of 100 is ",mean_rmse_spline_100, "thats is, ",mean_rmse_spline_100*100,"%\n\n")
mean_ioa_spline_100 = mean(ioa_spline_100_imputeTS)
cat("Mean IOA for na.spline method with Gap Value of 100 is ",mean_ioa_spline_100, "thats is, ",mean_ioa_spline_100*100,"%\n\n")
mean_mad_spline_100 = mean(mad_spline_100_imputeTS)
cat("Mean MAD for na.spline method with Gap Value of 100 is ",mean_mad_spline_100,"\n\n")
mad_spline_imputeTS = c(mad_spline_imputeTS,mean_mad_spline_100)
frac_bias_spline_imputeTS = c(frac_bias_spline_imputeTS,mean_fractional_bias_spline_100)
rmse_spline_imputeTS = c(rmse_spline_imputeTS,mean_rmse_spline_100)
ioa_spline_imputeTS = c(ioa_spline_imputeTS, mean_ioa_spline_100)
rm(temp1)
rm(temp2)
rm(temp3)
rm(temp4)
rm(x)
rm(i)
rm(j)
```

na.spline final values
```{r}
mad_spline_imputeTS
frac_bias_spline_imputeTS
rmse_spline_imputeTS
ioa_spline_imputeTS
```
